name: Build documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Trigger docs build
        run: ./scripts/travis_update_docs.sh
        env:
          TRAVIS_BRANCH: master
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
